server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          # default-label: config-server
          default-label: eureka-server
          uri: https://github.com/TCMP-DVelasco/microservicios
          search-paths: config-data
  application:
    name: config-service

